# Generated by Django 5.2.8 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('reset_password', 'Reset Password')], default='login', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['email', 'purpose', '-created_at'], name='users_emailv_email_2afafc_idx'),
                    models.Index(fields=['email', 'purpose', 'used_at', 'expires_at'], name='users_emailv_email_99017f_idx'),
                ],
            },
        ),
    ]
