# Generated by Django 5.2.8 on 2026-04-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_favorite_user_alter_postcontent_user_and_more'),
        ('users', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='users_email_email_4a7467_idx',
            old_name='users_emailv_email_2afafc_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='users_email_email_ca43d0_idx',
            old_name='users_emailv_email_99017f_idx',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
