# Generated by Django 5.2.8 on 2026-04-16

from django.db import migrations, models


def deduplicate_reports(apps, schema_editor):
    Report = apps.get_model('posts', 'Report')
    seen = set()
    # Keep earliest report record per (post_id, user_id), delete duplicates.
    for report in Report.objects.order_by('created_at', 'id').values('id', 'post_id', 'user_id'):
        key = (report['post_id'], report['user_id'])
        if key in seen:
            Report.objects.filter(id=report['id']).delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postreaction_remove_poststats_viewed_by'),
    ]

    operations = [
        migrations.RunPython(deduplicate_reports, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_user_report'),
        ),
    ]
